'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import StoreProvider from "./StoreProvider";
import { ThemeProvider } from 'next-themes';
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "IOT Magement",
//   description: "Generated by create next app",
//   icons: "/favicon.ico"
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>IOT Magement</title>
        <meta name="description" content="IOT Magement site" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <ThemeProvider attribute="class" defaultTheme='light'>


            {children}
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html >
  );
}
