{
 "title": "Data",
 "time": { "from": "2025-03-07T08:35:57.336Z", "to": "2025-03-07T08:45:57.336Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Light Level Device 4 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT value, \"createdAt\" FROM \"Timeseries\" WHERE (name = 'LIGHT_LEVEL' AND \"deviceId\" = 'dd3fa7a433cd4c1185d5c6fdacf30679') ORDER BY \"createdAt\" "
    }
   ]
  },
  {
   "title": "Humidity Device 4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT \"createdAt\", value, identifier FROM \"Timeseries\" WHERE (name = 'HUMIDITY' AND \"deviceId\" = 'dd3fa7a433cd4c1185d5c6fdacf30679') ORDER BY \"createdAt\" "
    }
   ]
  },
  {
   "title": "Sound Device 4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT value, \"createdAt\" FROM \"Timeseries\" WHERE (name = 'SOUND_LEVEL' AND \"deviceId\" = 'dd3fa7a433cd4c1185d5c6fdacf30679') ORDER BY \"createdAt\" "
    }
   ]
  },
  {
   "title": "Temp Device 4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT value, \"createdAt\" FROM \"Timeseries\" WHERE (name = 'TEMPERATURE' AND \"deviceId\" = 'dd3fa7a433cd4c1185d5c6fdacf30679') ORDER BY \"createdAt\" "
    }
   ]
  }
 ]
}